name: Build

on:
  push:
    branches:
    - dev
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        ref: dev
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3' # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Build Jekyll site
      run: |
        set -xo pipefail
        rm -rf _site/*
        gem install bundler
        bundle install
        bundle exec jekyll build
        cp CNAME _site/CNAME
    - name: Deploy
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        set -xo pipefail
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git pull
        git add .
        git commit -q -m "Website generated"
        git checkout dev
        git merge -s --allow-unrelated-histories ours origin/master
        git checkout master
        git pull
        git merge -X theirs dev
        ls -q | grep -v _site |  xargs rm -rf
        mv _site/* .
        rm -rf _site
        echo "mkalia.com" > CNAME
        [[ -n "$(git status --porcelain)" ]] || exit 0
        git add .
        git commit -m "Build $(git rev-parse source | grep -o '^.\{10\}')"
        git push "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" master

