name: Build

on:
  push:
    branches:
    - dev
jobs:
  build:
    runs-on: macos-11
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        ref: dev
    - name: Deploy
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        set -xo pipefail
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout master
        find . -name .jekyll-cache | xargs rm -rf
        find . -name .DS_Store | xargs rm -rf
        find . -name *.swp | xargs rm -rf
        ls -q | xargs rm -rf
        git add .
        git commit -m "Pre-deploy"
        git checkout dev
        git merge -s ours master
        git checkout master
        git pull
        git merge dev
        ls -q | grep -v _site |  xargs rm -rf
        mv _site/* .
        rm -rf _site
        echo "mkalia.com" > CNAME
        [[ -n "$(git status --porcelain)" ]] || exit 0
        git add .
        git commit -m "Build $(git rev-parse source | grep -o '^.\{10\}')"
        git push "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" master

